### ISSUE TITLE
ReferenceError: URI is not defined

### ISSUE THREAD

**Issue by 3wweiweiwu** [loadimpact/har-to-k6#59]
Hello,

I try to use har-to-k6 to create a javascript. One of the code looks like this:

    address = new URI(
      "https://azqamtell06/LoadReturn.htm"
    );
    address
      .addQuery("t", `${vars["VMName_25_Token"]}`)
      .addQuery("g", `${vars["VMName_25_GUID"]}`)
      .addQuery("pg", `${vars["VMName_25_PublicGUID"]}`)
      .addQuery("stoken", `${vars["VMName_25_SessionToken"]}`)

When I run the code, it gives following error:

ERRO[0063] ReferenceError: URI is not defined
        at file:///C:/Users/776ec4fd-12f6-4f41-ae01-89ea8b1efd82.js:895:19(2431)
        at github.com/loadimpact/k6/js/common.Bind.func1 (native)s
        at main (file:///C:/Users/776ec4fd-12f6-4f41-ae01-89ea8b1efd82.js:28:17(17))  executor=per-vu-iterations scenario=default source=stacktrace

**Comment by legander** [comment]
Thank you for reporting this issue, there is a PR that addresses this issue https://github.com/loadimpact/har-to-k6/pull/60
